export * from './analysis.interface';
export * from './analysis-doc.interface';
export * from './analysis-params.interface';
export * from './city-stats.interface';
export * from './city-stats-doc.interface';
export * from './district-stats.interface';
export * from './district-stats-doc.interface';
export * from './response.interface';
export * from './value-of';
