export const RANGE_FIELDS = [
  'publish_date',
  'price',
  'parking-places',
  'property-area',
  'ad_last_updated',
  'updated_at',
  'plot-area',
  'activeDays',
  'price-sqm',
];

export const NESTED_RANGE_FIELDS = [
  'priceDeviations.city_avg_mean.monthly_total.medianDelta',
  'priceDeviations.city_avg_mean.monthly_total.meanDelta',
  'priceDeviations.city_avg_mean.monthly_total.medianDeltaSqm',
  'priceDeviations.city_avg_mean.monthly_total.meanDeltaSqm',
  'priceDeviations.city_avg_mean.monthly_intermediary.medianDelta',
  'priceDeviations.city_avg_mean.monthly_intermediary.meanDelta',
  'priceDeviations.city_avg_mean.monthly_intermediary.medianDeltaSqm',
  'priceDeviations.city_avg_mean.monthly_intermediary.meanDeltaSqm',
  'priceDeviations.city_avg_mean.daily_total.medianDelta',
  'priceDeviations.city_avg_mean.daily_total.meanDelta',
  'priceDeviations.city_avg_mean.daily_total.medianDeltaSqm',
  'priceDeviations.city_avg_mean.daily_total.meanDeltaSqm',
  'priceDeviations.district_avg_mean.monthly_total.medianDelta',
  'priceDeviations.district_avg_mean.monthly_total.meanDelta',
  'priceDeviations.district_avg_mean.monthly_total.medianDeltaSqm',
  'priceDeviations.district_avg_mean.monthly_total.meanDeltaSqm',
  'priceDeviations.district_avg_mean.monthly_intermediary.medianDelta',
  'priceDeviations.district_avg_mean.monthly_intermediary.meanDelta',
  'priceDeviations.district_avg_mean.monthly_intermediary.medianDeltaSqm',
  'priceDeviations.district_avg_mean.monthly_intermediary.meanDeltaSqm',
  'priceDeviations.district_avg_mean.daily_total.medianDelta',
  'priceDeviations.district_avg_mean.daily_total.meanDelta',
  'priceDeviations.district_avg_mean.daily_total.medianDeltaSqm',
  'priceDeviations.district_avg_mean.daily_total.meanDeltaSqm',
];
