import type { Metadata } from 'next'
import './globals.scss'
import './layout.scss'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head></head>
    <body>
    <div id="root">
      <header>
        <div className="inner">
          <a className="logo" href="/">Logo</a>
          <div>Header</div>
        </div>
      </header>

      <div className="main-content">
        {children}
      </div>

      <footer>
        <div className="inner">
          <p>&copy; 2023 EstateIndex</p>
        </div>
      </footer>
    </div>
    </body>
    </html>
  )
}
