version: '3.8'

services:

  search-indexer:
    image: node:20-alpine
    working_dir: /search-indexer
    command: sh -c "npm i && npm run build && npm run start:prod"
    volumes:
      - .:/search-indexer
    hostname: localhost
    ports:
      - "${SEARCH_INDEXER_SERVICE_TCP_PORT}:${SEARCH_INDEXER_SERVICE_TCP_PORT}"
      - "${SEARCH_INDEXER_SERVICE_HTTP_PORT}:${SEARCH_INDEXER_SERVICE_HTTP_PORT}"
    env_file:
      - .env
    container_name: search-indexer
    networks:
      - common-net

networks:
  common-net:
    name: parser-network-1
    external: true
