import { filter, ignoreElements, of, switchMap, tap } from 'rxjs';

import { RealEstateObject } from '../../types/real-estate.type';
import { StoreEpic } from '../../types/store.types';
import { setLoader } from '../loader/loader.slice';

import { initBestPrices, setBestPrices } from './best-prices.slice';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
export const bestPricesEpic: StoreEpic = (action$, state$, { dispatch }) =>
  action$.pipe(
    filter(initBestPrices.match),
    tap(() => dispatch(setLoader({ key: 'best-prices', state: 'loading' }))),
    switchMap(() => {
      const RealEstateObjects: RealEstateObject[] = [
        {
          'url':
            'https://www.bazaraki.com/adv/4743488_2-bedroom-apartment-to-rent/',
          'title': '2-bedroom apartment to rent',
          'description':
            'Fully furnished 2 bedroom modern apartment Located in ayios dometios area near to supermarkets ,restaurants ,gas stations , cafes and a lot of amenities 10 minutes driving from downtown Smart home (iPad is provided ) Fully equipped kitchen Gas fire place Pros: very quiet neighborhood Cons: street parking Price: 1600/month No Agents Please',
          'city': 'Nicosia',
          'district': 'Egkomi',
          'publish_date': new Date('2023-06-13T12:39:00.000+00:00').getTime(),
          'price': 1600,
          'currency': 'EUR',
          'ad_id': '4743488',
          'online-viewing': 'No',
          'postal-code': '',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'A',
          'included': ['Alarm', 'Fireplace', 'Balcony'],
          'construction-year': '2017',
          'type': 'Apartment',
          'floor': '1st',
          'parking': 'Uncovered',
          'property-area': 155,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 2,
          'bathrooms': 2,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Not allowed',
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4734899_2-bedroom-apartment-to-rent/',
          'title': '2-bedroom apartment to rent',
          'description':
            '*AVAILABLE FROM THE 19TH OF AUGUST* **ONLY FOR LONG-TERM RENTAL** REAL LUXURY 2 BEDROOM APARTMENT IN PARALIMNI, IN A HIGH END COMPLEX €1000 (PLUS €100 FOR COMMUNAL FEES). TOTAL €1100 PER MONTH. REAL LUXURY APARTMENT IN MODERN LUXURY COMPLEX IN PARALIMNI, WITH EASY ACCESS TO PARALIMNI CENTER, PROTARAS AND AYIA NAPA. (THE ROOM USED CURRENTLY AS AN OFFICE WILL BE CHANGED AND WILL BECOME A BEDROOM.) BEDROOMS: 2 BATHROOMS: 2 FULLY FURNISHED FULLY AIR CONDITIONED (SPLIT SYSTEM) CEILING FANS IN BEDROOMS ALL ELECTRICAL APPLIANCES PRIVATE COVERED PARKING LARGE COMMUNAL SWIMMING POOL PRIVATE STORAGE ROOM (ON GROUND FLOOR) VERANDA BALCONY CORNER APARTMENT SECURITY DOOR IN BUILDING ENTRANCE PHONE/VIDEO INTERCOM ENTRY SYSTEM ELEVATOR OUTDOOR POOL SHOWERS OPEN PLAN LIVING, DINING AND KITCHEN AREAS MASTER BEDROOM WITH EN-SUITE BATHROOM FAMILY BATHROOM DOUBLE GLAZING THERMAL WINDOWS MOSQUITO/FLY NETS BLINDS THROUGHOUT BUILT-IN KITCHEN GRANITE KITCHEN COUNTERS KITCHEN ISLAND BREAKFAST BAR BUILT-IN WARDROBES SLIDING SHELVES AND SLIDING HANGERS IN WINDOWS VERANDA LOUNGE FURNITURE TENT SHADOWER ON VERANDA SLIDING SHADOWER ON BALCONY EXTERNAL LIGHTING SOLAR WATER HEATING SYSTEM ELECTRIC WATER HEATING SYSTEM WATER PRESSURIZING SYSTEM CUL DE SAC GATED COMPLEX QUIET COMPLEX QUIET LOCATION BRIGHT PANORAMIC VIEWS EASY ACCESS TO MAIN ROADS EASY ACCESS TO HIGHWAY CLOSE TO AMENITIES 2 MINUTES DRIVE TO PARALIMNI CENTER 3 MINUTE DRIVE TO PROTARAS 5 MINUTE DRIVE TO AYIA NAPA COVERED AREA: 86 SQ.M. VERANDA: 18 SQ.M. TOTAL AREA: 104 SQ.M. YEAR BUILT: 2020 CSC Zyprus Property Group LTD Licensed and Registered Real Estate Agency CREA Registration No. 742 and CREA License No. 378/E',
          'publish_date': new Date('2023-06-12T14:18:00.000Z').getTime(),
          'city': 'Famagusta',
          'district': 'Paralimni',
          'price': 1000,
          'currency': 'EUR',
          'ad_id': '4734899',
          'online-viewing': 'No',
          'postal-code': '',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'N/A',
          'included': ['Pool', 'Elevator', 'Balcony', 'Storage room'],
          'construction-year': '2020',
          'type': 'Apartment',
          'parking': 'Covered',
          'property-area': 104,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 2,
          'bathrooms': 2,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Not allowed',
          'coords': {
            lat: 35.0358446,
            lng: 33.9615927,
            latTitle: 'N',
            lngTitle: 'E',
          },
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4556702_3-bedroom-apartment-to-rent/',
          'title': '3-bedroom apartment to rent',
          'description':
            "MESSAGE ME ON WHATSUP ONLY PRIME DROSIA LOCATION FULLY FURNISHED. FANTASTIC 3 BEDROOM FLAT, LARGE KITCHEN, LIVING ROOM AND DINING ROOM, WITH PARK AND SALT LAKE VIEWS. OLDER BUILDINGS BUT COMPLETE RENOVATION. BRIGHT AND AIRY AND ROOMY, FEELS LIKE A HOUSE. FRESH PAINT, FULLY FURNISHED, NICE BALCONY OVERLOOKING THE PARK A MUST SEE TO APPRECIATE !!!!!!!! CATS OK. QUICK ACCESS TO ALL HIGHWAYS FIRST MONTH'S RENT PLUS SECURITY DEPOSIT",
          'publish_date': new Date('2023-06-15T13:18:00.000Z').getTime(),
          'city': 'Larnaca',
          'district': 'Agios Nikolaos',
          'price': 995,
          'currency': 'EUR',
          'ad_id': '4556702',
          'online-viewing': 'No',
          'postal-code': '',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'A',
          'included': ['Elevator', 'Balcony'],
          'construction-year': 'Older',
          'type': 'Apartment',
          'floor': '4th',
          'parking': 'Covered',
          'property-area': 125,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 3,
          'bathrooms': 2,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Allowed',
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4756139_1-bedroom-apartment-to-rent/',
          'title': '1-bedroom apartment to rent',
          'description':
            'Ενοικιάζεται μεζονέτα ενός υπνοδωματίου, πλήρως επιπλωμένη, σε συγκρότημα διαμερισμάτων λίγο έξω από το Παραλίμνι (κοντά στην εκκλησία Αγίας Βαρβάρας) και μερικά λεπτά μακριά από τις δημοφιλέστερες παραλίες της περιοχής, Αγία Τριάδα, Σειρήνα και Κάππαρη. Σε ήσυχη περιοχή που περιβάλλεται από πράσινο, με βεράντα και πρόσβαση στον κήπο. Στον πάνω όροφο, υπνοδωμάτιο και τουαλέτα, στο ισόγειο κουζίνα και καθιστικό με καναπέδες που γίνονται κρεβάτι. Πλησίον υπεραγοράς και άλλων υπηρεσιών. Χώρος στάθμευσης, διαθέσιμος. Ενοίκιο: 390 ευρώ το μήνα επί χρονιαίας βάσης. Πληροφορίες 99454589 (κα Ελευθερία Φλουρέντζου) One bedroom maisonette for rent - fully furnished in an apartment complex in Paralimni area (near Ayia Varvara church) - a few minutes away from the popular beaches of the area (Ayia Triada, Serena Bay and Kapparis). In a quiet area surrounded by green, with a terrace and garden access. The bedroom and toilet are located at the top floor and the kitchen and sofa-beds are located at the ground floor. Near a supermarket and other services. Parking space available. Rent: 390 EUR per month on a yearly basis. For more information contact: (Mrs Eleftheria Flourentzou)',
          'publish_date': new Date('2023-06-15T10:23:00.000Z').getTime(),
          'city': 'Famagusta',
          'district': 'Paralimni',
          'price': 390,
          'currency': 'EUR',
          'ad_id': '4756139',
          'online-viewing': 'No',
          'postal-code': '5291',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'N/A',
          'included': ['Garden', 'Balcony'],
          'construction-year': '2000',
          'type': 'Apartment',
          'floor': 'Ground floor',
          'parking': 'Uncovered',
          'property-area': 70,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 1,
          'bathrooms': 1,
          'air-conditioning': 'Partly',
          'pets': 'Not allowed',
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4729409_2-bedroom-apartment-to-rent/',
          'title': '2-bedroom apartment to rent',
          'description':
            'The apartment is situated in the tourist harbor area, the Limassol Marina. There are the best restaurants, bars, cozy cafes, green spaces, and walking paths. The apartment is fully furnished, decorated, and air-conditioned. The residents will enjoy a modern design, a cozy veranda with a sea view, and a perfect location with easy access to main roads. The facilities of the complex include a swimming pool with a relaxing zone and covered parking space.',
          'publish_date': new Date('2023-06-15T07:24:00.000Z').getTime(),
          'city': 'Limassol',
          'district': 'Limassol Marina',
          'price': 4500,
          'currency': 'EUR',
          'ad_id': '4729409',
          'online-viewing': 'No',
          'postal-code': '',
          'reference-number': '1704',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'N/A',
          'included': ['Pool'],
          'type': 'Apartment',
          'parking': 'Covered',
          'property-area': 80,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 2,
          'bathrooms': 2,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Not allowed',
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4711345_2-bedroom-apartment-to-rent/',
          'title': '2-bedroom apartment to rent',
          'description':
            'The ideal place for living. Limassol - Neapolis Location of the apartments: * 650 Meters to the sea * Quiet street * All infrastructure within walking distance - supermarkets, public transport Apartment and building: * After full renovation. No one lived in the apartment after the renovation. Bosch appliances, furnished, new windows and air conditioners * House 20+ in good technical condition * Elevator * Parking * The apartments are located on the 3rd floor out of 5 * 86 sq. m. covered area * 2 balconies * 1 WC * Title available',
          'publish_date': new Date('2023-06-15T06:51:00.000Z').getTime(),
          'city': 'Limassol',
          'district': 'Neapolis',
          'price': 2000,
          'currency': 'EUR',
          'ad_id': '4711345',
          'online-viewing': 'No',
          'postal-code': '',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'A',
          'included': ['Elevator', 'Balcony'],
          'type': 'Apartment',
          'floor': '3rd',
          'parking': 'Covered',
          'property-area': 86,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 2,
          'bathrooms': 1,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Allowed',
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4727800_3-bedroom-apartment-to-rent/',
          'title': '3-bedroom apartment to rent',
          'description':
            'Experience a modern style of living within Staycaee’s “Plus 25 Residence” apartment. You’ll love this fashionably furnished three-bedroom apartment with it’s modern décor, fully equipped kitchen and super stylish living room. Ideally located, you’re close to all the best that Limassol has to offer. Get a key and start enjoying the city’s charming vibes! Designed to make you feel at home! Thoughtfully designed with bespoke premium finishes, modern furnishings and fully equipped kitchen, you’ll enjoy that “Just bring your suitcase” and feel- like home philosophy that all Staycaee’s apartments and houses offer. Whether you’re lounging in your cosy living room enjoying the smart home system amenities or streaming the latest and greatest entertainment on the smart TV or getting some well- earned rest on the superior quality mattress with luxury linens, you’ll fall in love with everything this apartment has to offer. Apartment: -Smart TV -Full electrical appliances -Fully equipped kitchen -Washing machine -Dishwasher -Refrigerator -Fast internet -A/C in all areas -Alarm Extra reasons to live with us: -Ongoing support -Linen & Towels -Super-fast WiFi Building Amenities: -Cleaning services -Laundry services -Covered parking area Prime Location: Plus 25 is located in the center of Limassol, in a peaceful neighborhoodin Mesa Geitonia very near Brain Rocket new office and Makarios Ave.',
          'publish_date': new Date('2023-06-13T15:43:00.000Z').getTime(),
          'city': 'Limassol',
          'district': 'Mesa Geitonia',
          'price': 2600,
          'currency': 'EUR',
          'ad_id': '4727800',
          'online-viewing': 'No',
          'postal-code': '',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'A',
          'included': ['Elevator', 'Alarm', 'Balcony', 'Storage room'],
          'construction-year': '2022',
          'type': 'Apartment',
          'floor': '2nd',
          'parking': 'Covered',
          'property-area': 120,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 3,
          'bathrooms': 3,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Allowed',
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4702769_2-bedroom-apartment-to-rent/',
          'title': '2-bedroom apartment to rent',
          'description':
            "Experience a modern style of living within Staycaee's \"The One\" apartment. You'll love this fashionably furnished two-bedroom apartment with it's modern décor, fully equipped kitchen and super stylish living room. Ideally located, you're close to all the best that Limassol has to offer. Get a key and start enjoying the city's charming vibes! Apartment: -Smart TV -Full electrical appliances -Fully equipped kitchen -Washing machine -Dishwasher -Refrigerator -Fast internet -A/C in all areas -Entrance camera system Extra reasons to live with us: -Ongoing support -Linen & Towels -Super-fast WiFi Building Amenities: -Cleaning services -Laundry services -Covered parking area Prime Location: - Located in the tallest building of Limassol, The One Tower. - Few minutes away from Limassol's Historical center, Marina and the Tourist area. - Breathtaking sea view.",
          'publish_date': new Date('2023-06-13T11:56:00.000Z').getTime(),
          'city': 'Limassol',
          'district': 'Neapolis',
          'price': 7000,
          'currency': 'EUR',
          'ad_id': '4702769',
          'online-viewing': 'No',
          'postal-code': '',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'A',
          'included': ['Garden', 'Elevator', 'Balcony'],
          'type': 'Apartment',
          'parking': 'Covered',
          'property-area': 132,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 2,
          'bathrooms': 2,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Allowed',
          'coords': {
            lat: 34.6893639,
            lng: 33.0539774,
            latTitle: 'N',
            lngTitle: 'E',
          },
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4744227_1-bedroom-apartment-to-rent/',
          'title': '1-bedroom apartment to rent',
          'description':
            'A stylish and modernone bedroom flat is available for rent, located in an excellent location,very close to University of Nicosia, mall , super markets. schools, restaurants gym, all local amenities in walking distance.The flats comes furnished, floor to ceiling wardrobes, nice open plan kitchen and a comfortable living/dining room, large balcony overlooking the neighborhood.Flat is very bright and airy and in amazing condition.Living area around 50sq.m. and monthly rent of 650 euros, common expenses €30 extra., internet incl',
          'publish_date': new Date('2023-06-13T09:12:00.000Z').getTime(),
          'city': 'Nicosia',
          'district': 'Egkomi - Makedonitissa',
          'price': 650,
          'currency': 'EUR',
          'ad_id': '4744227',
          'online-viewing': 'No',
          'postal-code': '2417',
          'reference-number': '18006',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'In Progress',
          'included': [],
          'type': 'Apartment',
          'parking': 'Covered',
          'property-area': 45,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 1,
          'bathrooms': 1,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Not allowed',
          'coords': {
            lat: 35.1519834,
            lng: 33.2914495,
            latTitle: 'N',
            lngTitle: 'E',
          },
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4526344_2-bedroom-apartment-to-rent/',
          'title': '2-bedroom apartment to rent',
          'description':
            'Apartments in the Katholiki area in the city center. Nearby is a promenade leading to the "Marina of Limassol", ideal for jogging and walking. All necessary infrastructure is within walking distance. Spacious 2-bedroom apartment with two bathrooms (bath and shower), fully furnished: built-in furniture and Bosch appliances in the kitchen, built-in wardrobe in the hallway and bedrooms. Heated floors, laminate flooring in all living rooms, 2 covered verandas. Controlled entrance to the complex, closed parking and a hall with an elevator.',
          'publish_date': new Date('2023-06-12T07:41:00.000Z').getTime(),
          'city': 'Limassol',
          'district': 'Agia Zoni',
          'price': 3100,
          'currency': 'EUR',
          'ad_id': '4526344',
          'online-viewing': 'No',
          'postal-code': '',
          'reference-number': '1387',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'B',
          'included': ['Elevator'],
          'construction-year': '2022',
          'type': 'Apartment',
          'floor': '2nd',
          'parking': 'Covered',
          'property-area': 87,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 2,
          'bathrooms': 2,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Not allowed',
          'coords': {
            lat: 34.6842579,
            lng: 33.0387793,
            latTitle: 'N',
            lngTitle: 'E',
          },
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4535750_2-bedroom-apartment-to-rent/',
          'title': '2-bedroom apartment to rent',
          'description':
            'The apartments are located in Potamos Germasogeia near the beach and Dasoudi Park, convenient access to the highway along Kristaki Kranou Street and the embankment. Nearby there is all the necessary infrastructure within walking distance. New 2 bedroom apartment in a modern high-rise complex with a spacious kitchen-living room and cozy bedrooms with beautiful sea views and heated parquet floors in all living areas. Covered parking, swimming pool, gym and tennis court on site. Utilities are included in the rental price.',
          'publish_date': new Date('2023-06-12T07:41:00.000Z').getTime(),
          'city': 'Limassol',
          'district': 'Germasogeia Tourist Area',
          'price': 6500,
          'currency': 'EUR',
          'ad_id': '4535750',
          'online-viewing': 'No',
          'postal-code': '',
          'reference-number': '1400',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'N/A',
          'included': ['Pool', 'Garden', 'Elevator', 'Balcony'],
          'type': 'Apartment',
          'floor': '8th and above',
          'parking': 'Covered',
          'property-area': 81,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 2,
          'bathrooms': 1,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Not allowed',
          'coords': {
            lat: 34.700568,
            lng: 33.10234,
            latTitle: 'N',
            lngTitle: 'E',
          },
        },
        {
          'url':
            'https://www.bazaraki.com/adv/4724137_3-bedroom-apartment-to-rent/',
          'title': '3-bedroom apartment to rent',
          'description':
            'The spacious apartment is located on the beach line of the famous Neapolis area. All amenities, shops, pharmacies, schools, cafes and restaurants are within walking distance. The apartment has underfloor heating, VRV air-conditioning systems, and panoramic windows with double glazing in every room. Owners will enjoy a modern, premium high-rise building with hotel facilities. The infrastructure of the complex includes lobby, 24-hour concierge service, conference room, fitness center, spa, outdoor pool and underground parking space.',
          'publish_date': new Date('2023-06-12T07:41:00.000Z').getTime(),
          'city': 'Limassol',
          'district': 'Neapolis',
          'price': 12000,
          'currency': 'EUR',
          'ad_id': '4724137',
          'online-viewing': 'No',
          'postal-code': '',
          'reference-number': '1696',
          'square-meter-price': 0,
          'condition': 'Resale',
          'energy-efficiency': 'N/A',
          'included': ['Pool', 'Storage room'],
          'type': 'Apartment',
          'floor': '8th and above',
          'parking': 'Covered',
          'property-area': 150,
          'property-area-unit': 'm²',
          'furnishing': 'Fully Furnished',
          'bedrooms': 3,
          'bathrooms': 3,
          'air-conditioning': 'Full, all rooms',
          'pets': 'Not allowed',
        },
      ];

      return of(RealEstateObjects);
    }),
    tap(() => dispatch(setLoader({ key: 'best-prices', state: 'loaded' }))),
    tap((response) => dispatch(setBestPrices(response as RealEstateObject[]))),
    ignoreElements(),
  );
