import cloneDeep from 'lodash.clonedeep';

import { ISearchState } from './search.model';

import { getTodayEnd, getYearAgo } from '../../utils';


export const SEARCH_STATE_DEFAULT: ISearchState = {
  filters: {
    // Primary
    type: 'rent',
    city: null,
    district: null,
    bedrooms: { min: 0, max: 15 },
    bathrooms: { min: 0, max: 15 },
    'price-sqm': { min: 0, max: 3000 },
    price: { min: 0, max: 300_000 },

    // Special
    'priceDeviations.city_avg_mean.monthly_total.medianDelta': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.monthly_total.meanDelta': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.monthly_total.medianDeltaSqm': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.monthly_total.meanDeltaSqm': { min: 0, max: 400 },

    'priceDeviations.city_avg_mean.monthly_intermediary.medianDelta': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.monthly_intermediary.meanDelta': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.monthly_intermediary.medianDeltaSqm': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.monthly_intermediary.meanDeltaSqm': { min: 0, max: 400 },

    'priceDeviations.city_avg_mean.daily_total.medianDelta': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.daily_total.meanDelta': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.daily_total.medianDeltaSqm': { min: 0, max: 400 },
    'priceDeviations.city_avg_mean.daily_total.meanDeltaSqm': { min: 0, max: 400 },

    'priceDeviations.district_avg_mean.monthly_total.medianDelta': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.monthly_total.meanDelta': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.monthly_total.medianDeltaSqm': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.monthly_total.meanDeltaSqm': { min: 0, max: 400 },

    'priceDeviations.district_avg_mean.monthly_intermediary.medianDelta': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.monthly_intermediary.meanDelta': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.monthly_intermediary.medianDeltaSqm': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.monthly_intermediary.meanDeltaSqm': { min: 0, max: 400 },

    'priceDeviations.district_avg_mean.daily_total.medianDelta': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.daily_total.meanDelta': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.daily_total.medianDeltaSqm': { min: 0, max: 400 },
    'priceDeviations.district_avg_mean.daily_total.meanDeltaSqm': { min: 0, max: 400 },

    // Secondary
    source: null,
    'online-viewing': null,
    'postal-code': null,
    condition: null,
    'energy-efficiency': null,
    'construction-year': null,
    floor: null,
    parking: null,
    'parking-places': { min: 0, max: 8 },
    furnishing: null,
    'air-conditioning': null,
    pets: null,
    alarm: null,
    attic: null,
    balcony: null,
    elevator: null,
    fireplace: null,
    garden: null,
    playroom: null,
    pool: null,
    storage: null,
    'ad_last_updated': { min: getYearAgo(), max: getTodayEnd() },
    'updated_at': { min: getYearAgo(), max: getTodayEnd() },
    'plot-area': { min: 0, max: 100_000 },
    category: null,
    subcategory: null,
    activeDays: { min: 0, max: 365 },
  },
  sorts: {
    url: null,
    publish_date: null,
    source: null,
    city: 1,
    district: 1,
    price: null,
    'online-viewing': null,
    'postal-code': null,
    condition: null,
    'energy-efficiency': null,
    'construction-year': null,
    floor: null,
    parking: null,
    'parking-places': null,
    'property-area': null,
    furnishing: null,
    bedrooms: null,
    bathrooms: null,
    'air-conditioning': null,
    pets: null,
    alarm: null,
    attic: null,
    balcony: null,
    elevator: null,
    fireplace: null,
    garden: null,
    playroom: null,
    pool: null,
    storage: null,
    'ad_last_updated': null,
    'updated_at': null,
    'plot-area': null,
    category: null,
    subcategory: null,
    activeDays: null,
    'price-sqm': null,
    'priceDeviations.city_avg_mean.monthly_total.medianDelta': null,
    'priceDeviations.city_avg_mean.monthly_total.meanDelta': null,
    'priceDeviations.city_avg_mean.monthly_total.medianDeltaSqm': null,
    'priceDeviations.city_avg_mean.monthly_total.meanDeltaSqm': null,
    'priceDeviations.city_avg_mean.monthly_intermediary.medianDelta': null,
    'priceDeviations.city_avg_mean.monthly_intermediary.meanDelta': null,
    'priceDeviations.city_avg_mean.monthly_intermediary.medianDeltaSqm': null,
    'priceDeviations.city_avg_mean.monthly_intermediary.meanDeltaSqm': null,
    'priceDeviations.city_avg_mean.daily_total.medianDelta': null,
    'priceDeviations.city_avg_mean.daily_total.meanDelta': null,
    'priceDeviations.city_avg_mean.daily_total.medianDeltaSqm': null,
    'priceDeviations.city_avg_mean.daily_total.meanDeltaSqm': null,
    'priceDeviations.district_avg_mean.monthly_total.medianDelta': null,
    'priceDeviations.district_avg_mean.monthly_total.meanDelta': null,
    'priceDeviations.district_avg_mean.monthly_total.medianDeltaSqm': null,
    'priceDeviations.district_avg_mean.monthly_total.meanDeltaSqm': null,
    'priceDeviations.district_avg_mean.monthly_intermediary.medianDelta': null,
    'priceDeviations.district_avg_mean.monthly_intermediary.meanDelta': null,
    'priceDeviations.district_avg_mean.monthly_intermediary.medianDeltaSqm': null,
    'priceDeviations.district_avg_mean.monthly_intermediary.meanDeltaSqm': null,
    'priceDeviations.district_avg_mean.daily_total.medianDelta': null,
    'priceDeviations.district_avg_mean.daily_total.meanDelta': null,
    'priceDeviations.district_avg_mean.daily_total.medianDeltaSqm': null,
    'priceDeviations.district_avg_mean.daily_total.meanDeltaSqm': null,
  },
};

export const SEARCH_RENT_STATE_DEFAULT: ISearchState = {
  filters: {
    ...cloneDeep(SEARCH_STATE_DEFAULT.filters),
    type: 'rent',
  },
  sorts: {
    ...cloneDeep(SEARCH_STATE_DEFAULT.sorts),
  },
};

export const SEARCH_SALE_STATE_DEFAULT: ISearchState = {
  filters: {
    ...cloneDeep(SEARCH_STATE_DEFAULT.filters),
    type: 'sale',
  },
  sorts: {
    ...cloneDeep(SEARCH_STATE_DEFAULT.sorts),
  },
};
