version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: localhost
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    container_name: nginx
    volumes:
      - "/etc/nginx/ssl/${DOMAIN}:/etc/nginx/ssl/${DOMAIN}"
    networks:
       - common-net

networks:
  common-net:
    name: parser-network-1
    external: true
