import { IRentLimits } from '../types';


export const fallBackRentLimits = {
  'limits': {
    'source': [
      'bazaraki.com',
      'offer.com.cy',
    ],
    'online-viewing': [
      'No',
    ],
    'postal-code': [
      '85',
      '2350',
      '8500',
      '3081',
      '6051',
      '4170',
      '4521',
      '2334',
      '2044',
      '4157',
      '2324',
      '7562',
      '3601',
      '5330',
      '3036',
      '2644',
      '4540',
      '1036',
      '4043',
      '4067',
      '3112',
      '3201',
      '5295',
      '7520',
      '2123',
      '8820',
      '5289',
      '2572',
      '7733',
      '3300',
      '8570',
      '3051',
      '4044',
      '8607',
      '4840',
      '4520',
      '4047',
      '2304',
      '5522',
      '6031',
      '4531',
      '1010',
      '4603',
      '3106',
      '202',
      '45241',
      '4007',
      '8330',
      '4107',
      '3014',
      '3100',
      '4528',
      '1040',
      '2280',
      '6058',
      '8704',
      '4046',
      '3040',
      '2408',
      '2402',
      '4027',
      '2019',
      '4525',
      '3314',
      '7040',
      '3115',
      '2407',
      '8042',
      '2331',
      '3075',
      '4049',
      '3083',
      '4530',
      '8201',
      '4102',
      '2546',
      '3066',
      '8522',
      '3035',
      '3086',
      '2040',
      '4151',
      '2107',
      '6047',
      '2313',
      '8300',
      '4333',
      '1066',
      '2301',
      '7041',
      '2206',
      '4106',
      '4041',
      '2042',
      '4620',
      '4113',
      '1101',
      '7101',
      '7743',
      '4652',
      '2006',
      '2108',
      '7714',
      '7640',
      '4159',
      '52523',
      '2002',
      '4533',
      '2014',
      '4155',
      '8220',
      '2302',
      '2029',
      '3102',
      '3087',
      '4543',
      '2645',
      '3085',
      '4156',
      '7577',
      '3000',
      '2102',
      '2037',
      '4744',
      '3071',
      '3020',
      '4351',
      '3027',
      '5391',
      '1086',
      '2201',
      '8560',
      '7710',
      '6059',
      '2114',
      '2401',
      '4180',
      '6045',
      '3030',
      '6028',
      '8260',
      '2077',
      '8026',
      '2112',
      '6030',
      '6071',
      '4730',
      '3090',
      '4717',
      '2335',
      '2033',
      '4040',
      '2024',
      '3025',
      '4645',
      '2110',
      '7739',
      '8852',
      '4042',
      '6021',
      '2015',
      '3041',
      '8021',
      '1087',
      '2411',
      '3016',
      '4152',
      '6046',
      '3082',
      '3031',
      '8040',
      '4192',
      '2221',
      '7102',
      '1080',
      '6041',
      '1105',
      '2054',
      '6036',
      '2323',
      '0',
      '4005',
      '6010',
      '2660',
      '2735',
      '2836',
      '4100',
      '1045',
      '3165',
      '2220',
      '2039',
      '3105',
      '8250',
      '4820',
      '7877',
      '2361',
      '6050',
      '4191',
      '7081',
      '2121',
      '4651',
      '2058',
      '4150',
      '6042',
      '5736',
      '8650',
      '3026',
      '3045',
      '2232',
      '2416',
      '2413',
      '8280',
      '2023',
      '3065',
      '2003',
      '4529',
      '2417',
      '3060',
      '8723',
      '4710',
      '4507',
      '1916',
      '2043',
      '8510',
      '3033',
      '5320',
      '3067',
      '8016',
      '6052',
      '4878',
      '2373',
      '6022',
      '2018',
      '3080',
      '8025',
      '3042',
      '2415',
      '2045',
      '3091',
      '3055',
      '4050',
      '8036',
      '2305',
      '2400',
      '3052',
      '2321',
      '2360',
      '7716',
      '7570',
      '8270',
      '2064',
      '1056',
      '4771',
      '3017',
      '4105',
      '6013',
      '2007',
      '7730',
      '4506',
      '6025',
      '2365',
      '2480',
      '2325',
      '3022',
      '4045',
      '2202',
      '8549',
      '1046',
      '1027',
      '3096',
      '7104',
      '5291',
      '6023',
      '3118',
      '2800',
      '6060',
      '2062',
      '8035',
      '4549',
      '1047',
      '5380',
      '2055',
      '2008',
      '1021',
      '4534',
      '3101',
      '6037',
      '4002',
      '2314',
      '4104',
      '5282',
      '2021',
      '8200',
      '3050',
      '4566',
      '3047',
      '1060',
      '4003',
      '6015',
      '7103',
      '1071',
      '8049',
      '1048',
      '8509',
      '2540',
      '3095',
      '1020',
      '1234',
      '2115',
      '6012',
      '2300',
      '54041',
      '2222',
      '8048',
      '2333',
      '4532',
      '8207',
      '6040',
      '2113',
      '3076',
      '',
      '2000',
      '2643',
      '2406',
      '65500',
      '3311',
      '4716',
      '1095',
      '1057',
      '3318',
      '2332',
      '2057',
      '2101',
      '8504',
      '1011',
      '4654',
      '3021',
      '7649',
      '2450',
      '8020',
      '2364',
      '4006',
      '5390',
      '6080',
      '7540',
      '8015',
      '4193',
      '2060',
      '6011',
      '3120',
      '4187',
      '2231',
      '5280',
      '4632',
      '7060',
      '2049',
      '8046',
      '5290',
      '2046',
      '4154',
      '7080',
      '2034',
      '1075',
      '4130',
      '6053',
      '2671',
      '7560',
      '3046',
      '2363',
      '4004',
      '2059',
      '4871',
      '2001',
      '1055',
      '2012',
      '4184',
      '2311',
      '6020',
      '3011',
      '4103',
      '4522',
      '3969',
      '4000',
      '8041',
      '4048',
      '6301',
      '8221',
      '8065',
      '6017',
      '2409',
      '6056',
      '2425',
      '8045',
      '1508',
      '7550',
      '7000',
      '6018',
      '4607',
      '1035',
      '5757',
      '3117',
      '2532',
      '2028',
      '5292',
      '8642',
      '2038',
      '8577',
      '3107',
      '2103',
      '1090',
      '5297',
      '2065',
      '3110',
      '2013',
      '3048',
      '8873',
      '8027',
      '6027',
      '1026',
      '8540',
      '8700',
      '2051',
      '3061',
      '6035',
      '4527',
      '1025',
      '3077',
      '7100',
      '5510',
      '3064',
      '2109',
      '4194',
      '8011',
      '2020',
      '8884',
      '1065',
      '2035',
      '8290',
      '8575',
      '4636',
      '4153',
      '2200',
      '2368',
      '8573',
      '6043',
      '4630',
      '8010',
      '7731',
      '4747',
      '8028',
      '2235',
      '2027',
      '1076',
      '1041',
      '3032',
      '5294',
      '1061',
      '1082',
      '7737',
      '5296',
      '2369',
      '2460',
      '1070',
      '1077',
      '3012',
      '6057',
      '2414',
      '3111',
      '8574',
    ],
    'condition': [
      'Resale',
    ],
    'energy-efficiency': [
      'C',
      'A+',
      'D',
      'In Progress',
      'B',
      'N/A',
      'A',
      'B+',
      'E',
    ],
    'construction-year': [
      '2023',
      '2004',
      'Older',
      '1970',
      '1987',
      '1995',
      '1998',
      '2003',
      '2002',
      '2014',
      '1985',
      '2018',
      '2005',
      '2024',
      '2021',
      '1989',
      '2006',
      '1996',
      '1982',
      '1925',
      '1999',
      '2013',
      '2000',
      '1980',
      '2010',
      '1984',
      '2020',
      '2008',
      '1990',
      '2012',
      '2019',
      '2007',
      '2016',
      '2017',
      '1997',
      '2001',
      '1978',
      '2015',
      '1986',
      '1976',
      '2022',
      '2011',
      '1994',
      '2009',
      '1973',
      '1988',
      '1993',
    ],
    'floor': [
      '8th and above',
      '3rd',
      '2nd',
      '5th',
      '4th',
      '1st',
      'Ground floor',
      '7th',
      '6th',
    ],
    'parking': [
      'Uncovered',
      'No',
      'Covered',
    ],
    'parking-places': [
      2,
      3,
      4,
      1,
    ],
    'furnishing': [
      'Semi-Furnished',
      'Fully Furnished',
      'Unfurnished',
      'Appliances οnly',
    ],
    'bedrooms': [
      9,
      8,
      5,
      10,
      0,
      1,
      4,
      6,
      2,
      3,
      7,
    ],
    'bathrooms': [
      8,
      5,
      1,
      4,
      6,
      2,
      3,
      7,
    ],
    'air-conditioning': [
      'Partly',
      'Full, all rooms',
      'No',
    ],
    'pets': [
      'Not allowed',
      'Allowed',
    ],
    'alarm': [
      'No',
      'Yes',
    ],
    'attic': [
      'No',
      'Yes',
    ],
    'balcony': [
      'No',
      'Yes',
    ],
    'elevator': [
      'Yes',
      'No',
    ],
    'fireplace': [
      'No',
      'Yes',
    ],
    'garden': [
      'No',
      'Yes',
    ],
    'playroom': [
      'Yes',
      'No',
    ],
    'pool': [
      'Private',
      'No',
      'Yes',
      'Shared',
    ],
    'storage': [
      'Yes',
      'No',
    ],
  },
  'cities': [
    {
      'city': 'Famagusta',
      'districts': [
        'Achna',
        'Agia Napa',
        'Agia Thekla',
        'Agia Triada',
        'Agia Zoni',
        'Akropolis',
        'Avgorou',
        'Cape Greko',
        'Chrysospiliotissa',
        'Deryneia',
        'Frenaros',
        'Kapparis',
        'Konnos',
        'Liopetri',
        'Paralimni',
        'Pernera',
        'Profitis Elias',
        'Protaras',
        'Sotira',
        'Tremithousa',
        'Vrysoulles',
      ],
    },
    {
      'city': 'Nicosia',
      'districts': [
        'Ag Konst and Elenis',
        'Ag. Antonios',
        'Agia Eirini',
        'Agia Sofia',
        'Agia Varvara Lefkosias',
        'Agioi Omologites',
        'Agioi Trimithias',
        'Agios Andreas',
        'Agios Dometios - Agios Georgios',
        'Agios Dometios - Agios Pavlos',
        'Agios Epifanios Oreinis',
        'Agios Ioannis',
        'Agios Ioannis Malountas',
        'Agios Loukas',
        'Agios Savvas',
        'Agios Theodoros Soleas',
        'Agios Vasileios',
        'Aglantzia',
        'Akaki',
        'Alampra',
        'Alona',
        'Anageia',
        'Analiontas',
        'Arediou',
        'Askas',
        'Astromeritis',
        'Carolina Park',
        'Chrysaliniotissa',
        'Dali',
        'Dali - Ag Konst and Elenis',
        'Dali - Panag Evangelistria',
        'Deftera Kato',
        'Deftera Pano',
        'Deneia',
        'Egkomi',
        'Egkomi - Makedonitissa',
        'Egkomi - Parissinos',
        'Episkopeio',
        'Ergates',
        'Evrychou',
        'Faneromeni',
        'Flasou Kato',
        'GSP Area',
        'Geri',
        'Germasogeia',
        'Gourri',
        'Ilioupoli',
        'Kaimakli',
        'Kakopetria',
        'Kalithea',
        'Kalo Chorio',
        'Kalopanagiotis',
        'Kampi',
        'Kampia',
        'Kampos',
        'Kapedes',
        'Kataliontas',
        'Klirou',
        'Kokkinotrimithia',
        'Korakou',
        'Koutrafas Kato',
        'Lagoudera',
        'Lakatameia - Agia Paraskevi',
        'Lakatameia - Agios Mamas',
        'Lakatameia - Agios Nikolaos',
        'Lakatameia - Anthoupolis',
        'Latsia - Agios Eleftherios',
        'Latsia - Agios Georgios',
        'Latsia - Archangelos Michail',
        'Limassol - Agios Antonios',
        'Limassol - Mesa Geitonia',
        'Limassol - Omonia',
        'Livadia Lefkosias',
        'Lykabittos',
        'Lympia',
        'Lythrodontas',
        'Malounta',
        'Mammari',
        'Margi',
        'Mathiatis',
        'Meniko',
        'Mitsero',
        'Moni Kato',
        'Mosfili',
        'Moutoullas',
        'Mylikouri',
        'Nea Ledras',
        'Nikitari',
        'Nisou',
        'Omerie',
        'Ortakioi',
        'Pachyammos',
        'Palaichori Morfou',
        'Palaichori Oreinis',
        'Palaiometocho',
        'Palouriotissa',
        'Panagia',
        'Paphos - Agios Theodoros',
        'Pedoulas',
        'Pegeia',
        'Pentageia',
        'Pera',
        'Pera Chorio',
        'Peristerona Lefkosias',
        'Perivolia Larnakas',
        'Platanistasa',
        'Politiko',
        'Polystypos',
        'Potami',
        'Potamia',
        'Psimolofou',
        'Pyrgos Kato',
        'Sia',
        'Sinaoros',
        'Sopaz',
        'Sotira',
        'Spilia - Agios Antonios',
        'Stelmek Area',
        'Strovolos - Acropolis',
        'Strovolos - Agios Dimitrios',
        'Strovolos - Agios Vasileios',
        'Strovolos - Ap. Varnavas and Ag. Makar.',
        'Strovolos - Archangelos',
        'Strovolos - Chryseleousa',
        'Strovolos - Dasoupolis',
        'Strovolos - Enthomar Kyprianos',
        'Strovolos - Stavros',
        'Synoikismos Anthoupolis',
        'Temvria',
        'Trachoni Lefkosias',
        'Trypiotis',
        'Tseri',
        'Tymbou',
        'Vyzakia',
        'Walled Old City',
      ],
    },
    {
      'city': 'Paphos',
      'districts': [
        'Acheleia',
        'Agia Marina Chrysochous',
        'Agia Marina Kelokedaron',
        'Agia Marinouda',
        'Agia Varvara',
        'Agios Dimitrianos',
        'Agios Georgios',
        'Agios Nikolaos',
        'Agios Pavlos',
        'Agios Theodoros',
        'Akourdaleia Kato',
        'Akourdaleia Pano',
        'Akoursos',
        'Amargeti',
        'Anarita',
        'Anavargos',
        'Aphrodite hills Kouklia',
        'Archimandrita Kato',
        'Argaka',
        'Arminou',
        'Armou',
        'Arodes Kato',
        'Arodes Pano',
        'Asprogia',
        'Chlorakas',
        'Choletria',
        'Choulou',
        'Chrysochou',
        'Drouseia',
        'Drymou',
        'Eledio',
        'Empa',
        'Episkopi Pafou',
        'Fasli',
        'Filousa Kelokedaron',
        'Fyti',
        'Galataria',
        'Germasogeia',
        'Geroskipou',
        'Geroskipou - Neapolis',
        'Geroskipou Tourist Area',
        'Giolou',
        'Goudi',
        'Historical Center',
        'Ineia',
        'Kallepeia',
        'Kathikas',
        'Kato Paphos',
        'Kelokedara',
        'Kissonerga',
        'Koili',
        'Koilineia',
        'Koloni',
        'Konia',
        'Kouklia Pafou',
        'Kritou Tera',
        'Kynousa',
        'Lasa',
        'Latsi',
        'Lempa',
        'Letymvou',
        'Lysos',
        'Mandria Pafou',
        'Marathounta',
        'Mesa Chorio',
        'Mesogi',
        'Miliou',
        'Moutallos',
        'Nata',
        'Nea Dimmata',
        'Neo Chorio Pafou',
        'Nikokleia',
        'Panagia Kato',
        'Panagia Pano',
        'Pegeia',
        'Pentalia',
        'Peristerona Pafou',
        'Polemi',
        'Polis Chrysochous',
        'Pomos',
        'Prodromi',
        'Salamiou',
        'Simou',
        'Skoulli',
        'Statos - Agios Fotios',
        'Stroumpi Kato',
        'Stroumpi Pano',
        'Strovolos - Dasoupolis',
        'Tala',
        'Theletra',
        'Thrinia',
        'Timi',
        'Tombs Of the Kings',
        'Trachoni Lemesou',
        'Tremithousa',
        'Trimithousa',
        'Tsada',
        'Universal',
        'Vasiliko',
        'Venus Rock Kouklia',
      ],
    },
    {
      'city': 'Limassol',
      'districts': [
        'Agia Fyla',
        'Agia Napa',
        'Agia Paraskevi',
        'Agia Triada',
        'Agia Zoni',
        'Agios Amvrosios Lemesou',
        'Agios Antonios',
        'Agios Athanasios',
        'Agios Dimitrios',
        'Agios Georgios',
        'Agios Georgios(Fragk)',
        'Agios Ioannis',
        'Agios Mamas',
        'Agios Nektarios',
        'Agios Nicolaos',
        'Agios Pavlos',
        'Agios Spyridon',
        'Agios Stylianos',
        'Agios Therapon',
        'Agios Thomas',
        'Agios Tychon',
        'Agios Tychon Tourist Area',
        'Agridia',
        'Agros',
        'Akapnou',
        'Akrotiri',
        'Akrounta',
        'Alassa',
        'Amiantos Kato',
        'Anogyra',
        'Apesia',
        'Apostolos Andreas',
        'Apostolos Loukas',
        'Apsiou',
        'Arakapas',
        'Armenochori',
        'Arnaoutogeitonia',
        'Arsos Lemesou',
        'Asgata',
        'Asomatos Lemesou',
        'Avdimou',
        'Chalkoutsa',
        'Chandria',
        'Dierona',
        'Dora',
        'Doros',
        'Egkomi',
        'Ekali',
        'Episkopi Lemesou',
        'Eptagoneia',
        'Erimi',
        'Fasoula Lemesou',
        'Fasouri',
        'Foini',
        'Foinikaria',
        'Gerasa',
        'Germasogeia',
        'Germasogeia Tourist Area',
        'Historical Center',
        'Kalo Chorio Lemesou',
        'Kaminaria',
        'Kapileio',
        'Kapsalos',
        'Katholiki',
        'Kellaki',
        'Kivides Kato',
        'Kivides Pano',
        'Koilani',
        'Kolossi -Agios Loukas',
        'Kolossi -Apostolos Andreas',
        'Kontovathkeia',
        'Korfi',
        'Kouka',
        'Kyperounta',
        'Laneia',
        'Lemithou',
        'Limassol Marina',
        'Limnatis',
        'Linopetra',
        'Lofou',
        'Louvaras',
        'Mandria Lemesou',
        'Mathikoloni',
        'Mesa Geitonia',
        'Monagri',
        'Monagroulli',
        'Moni',
        'Moniatis',
        'Mouttagiaka',
        'Mouttagiaka Tourist Area',
        'Neapolis',
        'Omodos',
        'Omonia',
        'Pachna',
        'Palodeia',
        'Panag. Evangelistria',
        'Panagia Pano',
        'Panthea',
        'Paramali',
        'Paramytha',
        'Parekklisia',
        'Parekklisia Tourist Area',
        'Pelendri',
        'Pentakomo',
        'Pera Pedi',
        'Petrou Kai Pavlou',
        'Pissouri',
        'Platanisteia',
        'Platres Kato',
        'Platres Pano',
        'Polemidia - Agios Nikolaos',
        'Polemidia - Anthoupoli',
        'Polemidia - Apostolos Varnavas',
        'Polemidia - Archangelos Michail',
        'Polemidia - Makarios III',
        'Polemidia - Pan. Evangelistria',
        'Polemidia Kato',
        'Polemidia Pano',
        'Potamiou',
        'Potamos Germasogeias',
        'Prastio Avdimou',
        'Prastio Kellakiou',
        'Prodromos',
        'Profitis Ilias',
        'Pyrgos Lemesou',
        'Pyrgos Lemesou Tourist Area',
        'Saittas',
        'Sanida',
        'Silikou',
        'Sotira Lemesou',
        'Souni',
        'Spitali',
        'Sykopetra',
        'Timiou Prodromou  Mesa Geitonias',
        'Trachoni Lemesou',
        'Treis Elies',
        'Trimiklini',
        'Troodos',
        'Tserkez Tsiftlik (Tserkezoi)',
        'Tsiflikoudia',
        'Tsirion',
        'Tzami Tzentit',
        'Vasa Kellakiou',
        'Vasa Koilaniou',
        'Vouni',
        'Ypsonas',
        'Zakaki',
        'Zanakia',
        'Zoopigi',
      ],
    },
    {
      'city': 'Larnaca',
      'districts': [
        'Agia Anna',
        'Agioi Anargyroi I',
        'Agioi Anargyroi II',
        'Agioi Vavatsinias',
        'Agios Nikolaos',
        'Agios Theodoros',
        'Aglantzia',
        'Alaminos',
        'Alethriko',
        'Anafotida',
        'Anglisides',
        'Aradippou - Agios Fanourios',
        'Aradippou - Apostolos Loukas',
        'Aradippou - Vlachos',
        'Arch Makarios III',
        'Athienou',
        'Avdellero',
        'Choirokoitia',
        'Chrysopolitissa',
        'Dekeleia',
        'Dromolaxia',
        'Drosia',
        'Drys Kato',
        'Finikoudes',
        'Harbor',
        'Kalavasos',
        'Kalo Chorio',
        'Kamares',
        'Kiti',
        'Klavdia',
        'Kofinou',
        'Kokkines',
        'Kornos',
        'Lageia',
        'Lefkara Kato',
        'Lefkara Pano',
        'Livadia Larnakas',
        'Makenzy',
        'Maroni',
        'Mazotos',
        'Melini',
        'Meneou',
        'Mosfiloti',
        'Ora',
        'Ormideia',
        'Oroklini',
        'Oroklini Tourist Area',
        'Palouriotissa',
        'Perivolia Larnakas',
        'Protaras',
        'Psematismenos',
        'Psevdas',
        'Pyla',
        'Pyla Tourist Area',
        'Pyrga Larnakas',
        'Skala',
        'Skarinou',
        'Softades',
        'Sotiros',
        'Tersefanou',
        'Tochni',
        'Troulloi',
        'Tsakilero',
        'Vavatsinia',
        'Vavla',
        'Xylofagou',
        'Xylotymvou',
        'Zygi',
      ],
    },
  ],
  'categories': [
    {
      'category': 'houses',
      'subcategories': [
        'Detached house',
        'Not specified',
        'Villa',
        'Bungalo',
        'Semi-detached',
        'Maisonette',
      ],
    },
    {
      'category': 'apartments',
      'subcategories': [
        'Apartment',
        'Penthouse',
      ],
    },
  ],
  'ranges': {
    'priceRange': {
      'min': 0,
      'max': 250000,
    },
    'priceSqmRange': {
      'min': 0,
      'max': 3000,
    },
    'propertyAreaRange': {
      'min': 0,
      'max': 8500,
    },
    'plotAreaRange': {
      'min': 0,
      'max': 0,
    },
  },
} as unknown as IRentLimits;
