version: "3"
services:
  RCache:
    image: redis:7.0
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - .:/data
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
