version: '3.8'

services:

  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: analysis
    volumes:
      - .:/analysis
    hostname: localhost

networks:
  common-net:
    name: parser-network-1
    external: true
